version: '3'

services:
  db:
    image: neo4j:3.4
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
    ports:
      - "7474:7474/tcp"
      - "7687:7687/tcp"
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000/tcp"
    depends_on:
      - db